version: "3.9"
services:
  chatbot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=microsoft/DialoGPT-small
  mcp:
    build: .
    command: ["python", "app/mcp_server.py"]
    stdin_open: true
    tty: true